---
language: python

sudo: false

addons:
 apt:
   packages:
   - python-pip

install:
 # Install ansible
 - pip install ansible

 # Check ansible version
 - ansible --version

scripts:
- ansible-playbook -i "localhost," -c local ./tests/test.yml -v

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  on:
    tags: true