defaults: &defaults
  working_directory: &working_directory
    ~/ansible-role-telegraf

test_roles: &test_roles
  run:
    name: test ansible playbook
    command: |
      echo "orangesys_url: 'demo.i.orangesys.io'" >> defaults/main.yml
      echo "orangesys_jwt_token: '$ORANGESYS_JWT_TOKEN'" >> defaults/main.yml
      ansible-playbook -i "localhost," -c local ./tests/test-circleci.yml -v

yum-install-ansible: &yum-install-ansible
  run:
    name: Install ansible
    command: |
      yum install epel-release -y -q
      yum install ansible -y -q
      ansible --version

apt-get-ansible: &apt-get-ansible
  run:
    name: Install ansible
    command: |
      apt-get update -qyy
      apt-get install software-properties-common -qyy
      apt-add-repository ppa:ansible/ansible -y
      apt-get update -qyy
      apt-get install ansible -qyy
      ansible --version

checkout_cache_key: &checkout_cache_key v1-repo-{{ .Environment.CIRCLE_SHA1 }}
restore_checkout_cache: &restore_checkout_cache
  restore_cache:
    key: *checkout_cache_key

steps-centos: &steps-centos
  - checkout
  - *yum-install-ansible
  - *test_roles

steps-debian: &steps-debian
  - checkout
  - *apt-get-ansible
  - *test_roles    

version: 2

jobs:
  deps:
    <<: *defaults
    docker: 
      - image: centos:7
    steps:     
      - checkout
      - save_cache:
          key: *checkout_cache_key
          paths: *working_directory

  centos6:
    <<: *defaults
    docker:
      - image: centos:6
    steps: *steps-centos

  centos7:
    <<: *defaults
    docker:
      - image: centos:7
    steps: *steps-centos

  ubuntu14:
    <<: *defaults
    docker:
      - image: ubuntu:14.04
    steps: *steps-debian

  ubuntu16:
    <<: *defaults
    docker:
      - image: ubuntu:16.04
    steps: *steps-debian

  ubuntu18:
    <<: *defaults
    docker:
      - image: ubuntu:18.04
    steps: *steps-debian

workflows:
  version: 2
  telegraf:
    jobs:
      - 'deps'  
      - 'centos6':
          requires:
            - deps
      - 'centos7':
          requires:
            - deps
      - 'ubuntu14':
          requires:
            - deps
      - 'ubuntu16':
          requires:
            - deps
      - 'ubuntu18':
          requires:
            - deps