version: 2

references:
  container_config: &container_config
    test_roles: &test_roles
      run:
        name: test ansible playbook
        command: |
          ansible -m setup localhost
          ansible-playbook -i "localhost," -c local ./tests/test.yml -v
jobs:
  centos6:
    <<: *container_config
    docker:
      - image: centos:6
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            yum install epel-release -y -q
            yum install ansible -y -q
            ansible --version
      - *test_roles

  centos7:
    <<: *container_config
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            yum install epel-release -y -q
            yum install ansible -y -q
            ansible --version
      - *test_roles

  amzonlinux:
    <<: *container_config
    docker:
      - image: amzonlinux
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            rpm -ivh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
            yum install ansible -y -q
            ansible --version
      - *test_roles

  ubuntu14:
    <<: *container_config
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            sudo apt-get update
            sudo apt-get install software-properties-common
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt-get update
            sudo apt-get install ansible
            ansible --version
      - *test_roles

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - centos6
      - centos7
      - ubuntu14
      - amzonlinux