version: 2

jobs:
  centos6:
    docker:
      - image: centos6
    steps:
      - checkout
      - run:
          name: Install ansible
          command: |
            rpm -ivh http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
            yum install ansible -y
            ansible --version
      - run:
          name: Test roles
          command: |
            ansible-playbook ./tests/test.yml -i ./tests/inventory -v